#!/bin/sh

# Common shell aliases
# Sourced in both .bashrc and .zshrc

alias ls='ls --color=auto --group-directories-first'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias diff='diff --color=auto'

alias path='echo -e ${PATH//:/\\n}'

alias v='vim'
alias g='git'
alias z='zathura'

alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -vI'
alias mkdir='mkdir -pv'

alias ssn='sudo shutdown now'
alias sr='sudo reboot'
