#!/bin/sh

# Common shell aliases
# Sourced in both .bashrc and .zshrc

if [ -x "$(command -v exa)" ]; then
    alias ls='exa --icons --group-directories-first'
    alias ll='exa -lahF --icons --group-directories-first'
    alias la='exa -1a --icons --group-directories-first'
else
    alias ls='ls --color=auto --group-directories-first'
    alias ll='ls -alFh'
    alias la='ls -A'
fi

[ -x "$(command -v bat)" ] && alias cat='bat'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias diff='diff --color=auto'

alias path='echo -e ${PATH//:/\\n}'

alias v='vim'
alias g='git'
alias z='zathura'

alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -vI'
alias mkdir='mkdir -pv'

alias ssn='sudo shutdown now'
alias sr='sudo reboot'

# FUNCTIONS

# go to directories by fzf
gt() {
    cd $HOME && cd "$(find -type d | fzf --preview="tree -L 1 {}" --bind="space:toggle-preview" --preview-window=:hidden)" && echo "$PWD" && tree -C -L 1
}

# open document by fzf
doc() {
    filename="$(find $HOME -type f -name *.pdf | fzf)"
    [ -z $filename ] || devour zathura "$filename"
}

ex () {
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1   ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *.deb)       ar x $1      ;;
      *.tar.xz)    tar xf $1    ;;
      *.tar.zst)   unzstd $1    ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}
