#!/bin/bash

# Set shell prompt

# Get functions
[[ -f "$XDG_CONFIG_HOME/shell/functions" ]] && source "$XDG_CONFIG_HOME/shell/functions"

# Git prompt options
GIT_PS1_SHOWDIRTYSTATE=true
GIT_PS1_SHOWSTASHSTATE=true
GIT_PS1_SHOWUNTRACKEDFILES=true
GIT_PS1_SHOWUPSTREAM="auto"
GIT_PS1_HIDE_IF_PWD_IGNORED=true
GIT_PS1_SHOWCOLORHINTS=true
[[ -f "$XDG_CONFIG_HOME/git/git-prompt.sh" ]] && source "$XDG_CONFIG_HOME/git/git-prompt.sh"

## Prompts
export PROMPT_DIRTRIM=2

# Basic prompt
_basic_pre='[\u@\h \W]'
_basic_post='\$ '

# Minimal prompt
_minimal_pre=' \[\033[1;36m\]\w \[\033[0m\]'
_minimal_post='\[\033[1;36m\]>\[\033[1;34m\]>\[\033[0m\] '

# Classic Ubuntu/Debian prompt
_debian_pre='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[0m\]'
_debian_post='\[\033[1;37m\]\[\033[00m\]\$ '

# Two-line prompt
_2line_pre='\[\033[;32m\]┌──(\[\033[1;34m\]\u@\h\[\033[;32m\])-[\[\033[0;1m\]\w\[\033[;32m\]]\[\033[0m\]'
_2line_post='\n\[\033[;32m\]└─\[\033[1;34m\]\$\[\033[0m\] '

# Colorful prompt
_colorful_pre='\[\033[1m\]\[\033[1;31m\][\[\033[01;33m\]\u\[\033[11;32m\]@\[\033[11;34m\]\h \[\033[1;35m\]\W\[\033[1;31m\]]\[\033[0m\]'
_colorful_post='\[\033[1;37m\]\$ \[\033[0m\]'

pre_prompt=$_colorful_pre
post_prompt=$_colorful_post

MY_HOSTNAME="ThinkPad-E15-Gen-4"
if [[ $HOSTNAME =~ $MY_HOSTNAME ]]; then
    # currently on my personal machine
    if [[ $HOSTNAME == $MY_HOSTNAME ]]; then
	# match exactly -> not in a distrobox container
	pre_prompt=$_minimal_pre
	post_prompt=$_minimal_post
    else
	# differentiate distrobox by prompt
	os=$(get_os 2>/dev/null)
	if [[ $os =~ "Ubuntu" || $os =~ "Debian" ]]; then
	    pre_prompt=$_debian_pre
	    post_prompt=$_debian_post
	elif [[ $os =~ "Arch Linux" || $os =~ "Fedora" ]]; then
	    pre_prompt=$_colorful_pre
	    post_prompt=$_colorful_post
	else 
	    pre_prompt=$_2line_pre
	    post_prompt=$_2line_post
	fi
    fi
else 
    # not on my personal machine -> default to the Debian prompt
    pre_prompt=$_debian_pre
    post_prompt=$_debian_post
fi

# use git prompt when possible
if [[ "$(declare -F __git_ps1)" ]]; then
    # by using PROMPT_COMMAND, tools that manipulating PS1 such as `venv` and `conda` won't work
    # export PROMPT_COMMAND='__git_ps1 "$pre_prompt" "$post_prompt"'
    PS1="${pre_prompt}\$(__git_ps1)${post_prompt}"
else
    PS1="${pre_prompt}${post_prompt}"
fi

export PS1
