#!/bin/sh

# Common env variables and path for both bash and zsh
# Sourced in both .bash_profile and .zshenv

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi
if [ -d "$HOME/.local/scripts" ] ; then
    PATH="$HOME/.local/scripts:$PATH"
fi
if [ -d "/var/lib/flatpak/exports/bin" ] ; then
    PATH="$PATH:/var/lib/flatpak/exports/bin"
fi
export PATH

# source to get common shell functions
[ -f $HOME/.config/shell/functions ] && . $HOME/.config/shell/functions

# Common program
export EDITOR="nvim"
export VISUAL="nvim"
export TERMINAL="kitty"
export BROWSER="brave-browser"
export PAGER="less"
if has bat
then
    export PAGER="bat"
    export BAT_PAGER="less"
    export MANROFFOPT="-c"
    export MANPAGER="sh -c 'col -bx | bat -l man -p'"
fi
if has batcat
then
    export PAGER="batcat"
    export BAT_PAGER="less"
    export MANROFFOPT="-c"
    export MANPAGER="sh -c 'col -bx | batcat -l man -p'"
fi
has zathura && export READER="zathura"

# Clean up with XDG
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${HOME}/.local/state"
export GTK2_RC_FILES="${XDG_CONFIG_HOME}/gtk-2.0/gtkrc-2.0"
export WGETRC="${XDG_CONFIG_HOME}/wget/wgetrc"
export INPUTRC="${XDG_CONFIG_HOME}/shell/inputrc"
export GNUPGHOME="${XDG_DATA_HOME}/gnupg"
export RXVT_SOCKET="${XDG_RUNTIME_DIR}/urxvtd"
export TERMINFO="$XDG_DATA_HOME"/terminfo
export TERMINFO_DIRS="$XDG_DATA_HOME"/terminfo:/usr/share/terminfo

# ibus daemon
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT4_IM_MODULE=ibus
export CLUTTER_IM_MODULE=ibus
export GLFW_IM_MODULE=ibus          # for kitty terminal

# FZF
has fd && export FZF_DEFAULT_COMMAND='fd --type f'
has ag && export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse'
export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -200'"

# Various programming tools

# conda
[[ -f "$HOME/.conda/etc/profile.d/conda.sh" ]] && . $HOME/.conda/etc/profile.d/conda.sh

# cargo
[[ -f "$HOME/.cargo/env" ]] && . $HOME/.cargo/env

# ghcup-env
[[ -f "$HOME/.ghcup/env" ]] && source "$HOME/.ghcup/env"

# npm
export NPM_CONFIG_PREFIX=$HOME/.npm-global
