#!/bin/sh

# Common env variables and path for both bash and zsh
# Sourced in both .bash_profile and .zshenv,
# so keep this POSIX compliant

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi
if [ -d "$HOME/.local/scripts" ] ; then
    PATH="$HOME/.local/scripts:$PATH"
fi
export PATH

# Common program
export EDITOR="vim"
export VISUAL="vim"
export TERMINAL="alacritty"
export BROWSER="firefox"
export PAGER="less"
[ -x "$(command -v bat)" ] && export PAGER="bat" && export BAT_PAGER="less"
[ -x "$(command -v batcat)" ] && export PAGER="batcat" && export BAT_PAGER="less"
export READER="zathura"

# Clean up with XDG
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:="$HOME/.config"}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:="$HOME/.cache"}
export XDG_DATA_HOME=${XDG_DATA_HOME:="$HOME/.local/share"}
export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"
export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc"
export GNUPGHOME="${XDG_DATA_HOME}/gnupg"
export RXVT_SOCKET="${XDG_RUNTIME_DIR}/urxvtd"
export TERMINFO="$XDG_DATA_HOME"/terminfo
export TERMINFO_DIRS="$XDG_DATA_HOME"/terminfo:/usr/share/terminfo
export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'

# ibus daemon
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT4_IM_MODULE=ibus
export CLUTTER_IM_MODULE=ibus

# FZF
[ -x "$(command -v fd)" ] && export FZF_DEFAULT_COMMAND='fd --type f'
[ -x "$(command -v ag)" ] && export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse'
export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -200'"
