"
" .vimrc
"

" First thing first,
set nocompatible
filetype plugin on
syntax on

set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after

let g:netrw_home = $XDG_DATA_HOME."/vim"
call mkdir($XDG_DATA_HOME."/vim/spell", 'p')
set viewdir=$XDG_DATA_HOME/vim/view | call mkdir(&viewdir, 'p')

set backupdir=$XDG_CACHE_HOME/vim/backup | call mkdir(&backupdir, 'p')
set directory=$XDG_CACHE_HOME/vim/swap   | call mkdir(&directory, 'p')
set undodir=$XDG_CACHE_HOME/vim/undo     | call mkdir(&undodir,   'p')

if !has('nvim') | set viminfofile=$XDG_CACHE_HOME/vim/viminfo | endif

let mapleader=" "

call plug#begin()

" colorschemes
Plug 'safv12/andromeda.vim'
Plug 'tomasr/molokai'
Plug 'sonph/onehalf', {'rtp': 'vim/'}
Plug 'sjl/badwolf'
Plug 'NLKNguyen/papercolor-theme'

" Git-related
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'

" Directory tree
Plug 'scrooloose/nerdtree'

" Fuzzy search
Plug 'ctrlpvim/ctrlp.vim'

" Quick closing
Plug 'mhinz/vim-sayonara', { 'on': 'Sayonara' }

" status bar
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" Code auto-comment
Plug 'preservim/nerdcommenter'

" Python syntax highlighting
Plug 'vim-python/python-syntax'

" Horizontal movement
Plug 'unblevable/quick-scope'

Plug 'tpope/vim-surround'

" Linting
Plug 'dense-analysis/ale'

call plug#end()


" General settings
set number              " show line number
set relativenumber      " relative number line
set showcmd             " show command in bottom bar
set cursorline          " highlight current line
set cursorcolumn        " highlight current column
filetype indent on      " load filetype-specific indent file
set lazyredraw          " redraw only when need to
set showmatch           " highlight matching brackets

set tabstop=4           " number of visual spaces per tab
set softtabstop=4       " number of space in tab when editing
set shiftwidth=4
set smartindent
set smarttab            " insert/delete n spaces for tab
set autoindent
set expandtab           " tabs are spaces

set incsearch           " search as characters are entered
set nohlsearch          " not highlight matches in search
set noerrorbells

set nowrap
set scrolloff=999

set signcolumn=yes
set colorcolumn=80

set encoding=utf-8

set background=dark

set splitbelow
set splitright

set laststatus=2
set t_Co=256

" set theme for status line
let g:airline_powerline_fonts = 1
let g:airline_theme='powerlineish'
let g:airline_left_sep=''          " powerline symbols

" Airline's smart tabline
let g:airline#extensions#tabline#enabled = 1

" Airline with ALE
let g:airline#extensions#ale#enabled = 1

" set nerdtree size
let g:NERDTreeWinSize=20

" show hidden file in nerdtree
let g:NERDTreeShowHidden=1

" python with virtualenv support
if has('python3')
py3 << EOF
import os
import sys
if 'VIRTUAL_ENV' in os.environ:
    env_base_dir = os.environ['VIRTUAL_ENV']
    activate_this = os.path.join(env_base_dir, 'bin/activate_this.py')
    exec(open(activate_this).read(), dict(__file__=activate_this))
EOF
endif

" ALE settings
" ALE fixing:
let g:ale_fixers = {
\   '*': ['remove_trailing_lines', 'trim_whitespace'],
\   'python': ['black'],
\}
let g:ale_fix_on_save = 1
" ALE linting:
let g:ale_linter = {
\   'python': ['flake8', 'mypy'],
\}
let g:ale_linter_explicit = 1

" Disable auto-detection of virtualenv,
" so $VIRTUAL_ENV is always used
let g:ale_virtualenv_dir_names = []
let g:ale_python_flake8_options = '--max-line-length=88'

" Cursor shape
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"

" Keybindings

" Back to normal
inoremap jk <Esc>

" Quickly access .vimrc
nnoremap <Leader>ev :edit $MYVIMRC<CR>
nnoremap <Leader>sv :source $MYVIMRC<CR>

" Write and quit
nnoremap <Leader>q :w<CR>:Sayonara<CR>
nnoremap <Leader><Leader>q :Sayonara<CR>
nnoremap <Leader>w :w<CR>

" Open splits
nnoremap <Leader><Leader>s :split<CR>
nnoremap <Leader><Leader>v :vsplit<CR>

" Buffer navigations
nnoremap <Leader><Tab> <C-^>
nnoremap <Tab> :bn<CR>

" Quick git
nnoremap <Leader><Leader>g :Git<CR>

" Fuzzy search
nnoremap <Leader>p :CtrlP<CR>

" Move visual line
nnoremap j gj
nnoremap k gk

" Navigating splits
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Make Y behavior consistent with others
nnoremap Y y$

" Move to begin or end of line easier
nnoremap H ^
nnoremap L $

" Toggle NERDTree
nnoremap <Leader><Leader>n :NERDTreeToggle<CR>

" Auto center the screen when enter insert mode
autocmd InsertEnter * norm zz

" Access system clipboard, Ctrl+Alt+C and Ctrl+Alt+V to copy and paste
set clipboard+=unnamedplus
vnoremap <C-M-c> "+y
nnoremap <C-M-v> "+P

" Automatically deletes all trailing whitespaces and newlines at end of file
" on save
autocmd BufWritePre * %s/\s\+$//e
autocmd BufWritePre * %s/\n\+\%$//e
autocmd BufWritePre *.[ch] %s/\%$/\r/e

" Python-syntax plugin
let g:python_highlight_all = 1

" Quickscope
" Trigger a highlight in the appropriate direction when pressing these
let g:qs_highlight_on_keys = ['f', 'F', 't', 'T']
let g:qs_max_chars=120
augroup qs_color
    autocmd!
    autocmd ColorScheme * highlight QuickScopePrimary guifg='#afff5f' gui=underline ctermfg=155 cterm=underline
    autocmd ColorScheme * highlight QuickScopeSecondary guifg='#5fffff' gui=underline ctermfg=81 cterm=underline
augroup END

colorscheme PaperColor


" Enable autocompletion
set wildmenu
set wildmode=longest,list,full
set completeopt=menuone,longest

" Minimalist-TabComplete-Plugin
inoremap <expr> <Tab> TabComplete()
fun! TabComplete()
    if getline('.')[col('.') - 2] =~ '\K' || pumvisible()
        return "\<C-P>"
    else
        return "\<Tab>"
    endif
endfun

" Minimalist-AutoCompletePop-Plugin
set completeopt=menu,menuone,noinsert
inoremap <expr> <CR> pumvisible() ? "\<C-Y>" : "\<CR>"
autocmd InsertCharPre * call AutoComplete()
fun! AutoComplete()
    if v:char =~ '\K'
        \ && getline('.')[col('.') - 4] !~ '\K'
        \ && getline('.')[col('.') - 3] =~ '\K'
        \ && getline('.')[col('.') - 2] =~ '\K' " last char
        \ && getline('.')[col('.') - 1] !~ '\K'

        call feedkeys("\<C-P>", 'n')
    end
endfun

" set linewrap in markdown and latex file
autocmd BufRead,BufNewFile *.md,*.tex set wrap

let g:gitgutter_map_keys = 0
highlight GitGutterAdd guifg=#009900 ctermfg=Green
highlight GitGutterChange guifg=#bbbb00 ctermfg=Yellow
highlight GitGutterDelete guifg=#ff2222 ctermfg=Red

augroup git_gutter
    autocmd!
    autocmd BufWritePost * :GitGutter
augroup END
